[package]
name = "leetcode_scaffold"
version = "0.0.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
regex = "1.10.5"
ureq = { version = "2.9.7", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde-query = "0.2.0"
serde_json = "1.0.117"
